export const accessoryDataTemplate_optics:{name:string, de:string, en:string, fr:string, it: string, ch: string}[] = [
        {
                name: "manufacturer",
                de: "Hersteller",
                en: "Manufacturer",
                fr: "Fabricant",
                it: "Produttore",
                ch: "Producent",
        },
        {   
                name: "designation",
                de: "Bezeichnung",
                en: "Designation",
                fr: "Désignation",
                it: "Denominazione",
                ch: "Designaziun",
        },
        {
                name: "type",
                de: "Typ",    
                en: "Origin Country",
                fr: "Pays d'origine",
                it: "Paese di origine",
                ch: "Pajais d'origin",
        },
        {
                name: "reticle",
                de: "Absehen",
                en: "Caliber",
                fr: "Calibre",
                it: "Calibro",
                ch: "Caliber",
        },
        {
                name: "clicksVert",
                de: "Klicks Höhe",
                en: "Headstamp",
                fr: "Cachet",
                it: "Punzonatura",
                ch: "Palantschieu sura",
        },
        {
            name: "clicksHor",
            de: "Klicks Seite",
            en: "Current stock",
            fr: "Montant actuel",
            it: "Quantità attuale",
            ch: "Quantitad actuala",
    },
    {
        name: "acquisitionDate",
        de: "Erwerbsdatum",
        en: "Last change of stock",
        fr: "Dernier changement de quantité",
        it: "Ultima variazione di quantità",
        ch: "Ultima midada da la quantitad",
    },
    {
        name: "lastBatteryChangeAt",
        de: "Letzter Batteriewechsel",
        en: "Critical stock",
        fr: "Quantité critique",
        it: "Scorta critica",
        ch: "Quantitad critica",
    },
    {
        name: "paidPrice",
        de: "Preis",
        en: "Critical stock",
        fr: "Quantité critique",
        it: "Scorta critica",
        ch: "Quantitad critica",
    },
    {
        name: "boughtFrom",
        de: "Gekauft von",
        en: "Critical stock",
        fr: "Quantité critique",
        it: "Scorta critica",
        ch: "Quantitad critica",
    },
    {
        name: "marketValue",
        de: "Wert",
        en: "Critical stock",
        fr: "Quantité critique",
        it: "Scorta critica",
        ch: "Quantitad critica",
    },
    {
        name: "currentlyMountedOn",
        de: "Momentan montiert auf",
        en: "Critical stock",
        fr: "Quantité critique",
        it: "Scorta critica",
        ch: "Quantitad critica",
    },
    ]
    
    export const accessoryRemarks_optics:{name:string, de:string, en:string, fr:string, it: string, ch:string} = {
        name: "remarks",
        de: "Bemerkungen",
        en: "Remarks",
        fr: "Remarques",
        it: "Osservazioni",
        ch: "Remartgar",
    }
    
    export const accessoryDataTemplate_magazines:{name:string, de:string, en:string, fr:string, it: string, ch: string}[] = [
        {
                name: "manufacturer",
                de: "Hersteller",
                en: "Manufacturer",
                fr: "Fabricant",
                it: "Produttore",
                ch: "Producent",
        },
        {   
                name: "designation",
                de: "Bezeichnung",
                en: "Designation",
                fr: "Désignation",
                it: "Denominazione",
                ch: "Designaziun",
        },
        {
                name: "platform",
                de: "Plattform",    
                en: "Origin Country",
                fr: "Pays d'origine",
                it: "Paese di origine",
                ch: "Pajais d'origin",
        },
        {
                name: "capacity",
                de: "Kapazität",
                en: "Caliber",
                fr: "Calibre",
                it: "Calibro",
                ch: "Caliber",
        },
    {
        name: "acquisitionDate",
        de: "Erwerbsdatum",
        en: "Last change of stock",
        fr: "Dernier changement de quantité",
        it: "Ultima variazione di quantità",
        ch: "Ultima midada da la quantitad",
    },
    {
        name: "paidPrice",
        de: "Preis",
        en: "Critical stock",
        fr: "Quantité critique",
        it: "Scorta critica",
        ch: "Quantitad critica",
    },
    {
        name: "boughtFrom",
        de: "Gekauft von",
        en: "Critical stock",
        fr: "Quantité critique",
        it: "Scorta critica",
        ch: "Quantitad critica",
    },
    {
        name: "marketValue",
        de: "Wert",
        en: "Critical stock",
        fr: "Quantité critique",
        it: "Scorta critica",
        ch: "Quantitad critica",
    },
    {
        name: "stock",
        de: "Bestand",
        en: "Critical stock",
        fr: "Quantité critique",
        it: "Scorta critica",
        ch: "Quantitad critica",
    },
    ]
    
    export const accessoryRemarks_magazines:{name:string, de:string, en:string, fr:string, it: string, ch:string} = {
        name: "remarks",
        de: "Bemerkungen",
        en: "Remarks",
        fr: "Remarques",
        it: "Osservazioni",
        ch: "Remartgar",
    }
    