export const calibers:{range:string, variants: {name: string}[]}[] = [
    {
        range: "2mm (.79 - .117)",
        variants: [
            {"name": "2mm pinfire"},
            {"name": "2.34mm rimfire"},
            {"name": ".10 Eichelberger Long Rifle"},
            {"name": ".10 Eichelberger Pup"},
            {"name": ".10 Eichelberger Squirrel"},
            {"name": "2mm Kolibri"}
          ],
    },
    {
        range: "3mm (.118 - .156)",
        variants: [
            {"name": ".12 Cooper"},
            {"name": ".12 Eichelberger Carbine"},
            {"name": ".12 Eichelberger Long Rifle"},
            {"name": ".12 Eichelberger Win Mag RF"},
            {"name": ".14 Cooper"},
            {"name": ".14 Eichelberger Bee"},
            {"name": ".14 Eichelberger Dart"},
            {"name": ".14 Jet Junior"},
            {"name": ".14 Walker Hornet"},
            {"name": ".14-222"},
            {"name": ".14/222 Eichelberger Mag"},
            {"name": "3mm Kolibri"},
            {"name": "3mm US"}
          ],
    },
    {
        range: "4mm (.157 - .196)",
        variants: [
            {"name": ".17 Mach 2"},
            {"name": ".17 HMR"},
            {"name": ".17 PMC/Aguila"},
            {"name": ".17 Winchester Super Magnum"},
            {"name": "4mm Lienhard"},
            {"name": "4.5×26mm MKR"},
            {"name": "4.25mm Liliput"},
            {"name": "4.38×30mm Libra"},
            {"name": "4.5x40mmR"},
            {"name": "4.6×30mm HK"},
            {"name": ".17 Bumble Bee"},
            {"name": "4mm M20 (4×10 mm)"},
            {"name": ".17 Hornet"},
            {"name": ".17 Mach IV"},
            {"name": ".17 Remington"},
            {"name": ".17 Remington Fireball"},
            {"name": ".17 Ackley Bee"},
            {"name": "4.6×36mm"},
            {"name": "4.85×49mm"}
          ],
    },
    {
        range: "5mm (.197 - .235)",
        variants: [
            {"name": "5mm Remington Rimfire Magnum"},
            {"name": ".21 Sharp"},
            {"name": ".22 BB"},
            {"name": ".22 CB"},
            {"name": ".22 Short"},
            {"name": ".22 Long"},
            {"name": ".22 Long Rifle"},
            {"name": ".22 Winchester Rimfire"},
            {"name": ".22 Remington Special"},
            {"name": ".22 Winchester Magnum Rimfire (.22 Magnum)"},
            {"name": "5mm Clement"},
            {"name": "5mm Bergmann"},
            {"name": "5mm Bergmann Rimless"},
            {"name": "5.45×18mm Soviet"},
            {"name": ".22 TCM"},
            {"name": "FN 5.7×28mm"},
            {"name": "5.8×21mm"},
            {"name": "5mm Pickert"},
            {"name": ".22 Remington Jet"},
            {"name": "5.5mm Velo Dog"},
            {"name": "5.43mm Louis Mattis"},
            {"name": ".19 Calhoon Hornet"},
            {"name": ".19 Badger"},
            {"name": ".19-223"},
            {"name": "5mm Craig"},
            {"name": ".20 VarTarg"},
            {"name": "5mm/35 SMc"},
            {"name": ".20 Tactical"},
            {"name": ".204 Ruger"},
            {"name": "20 Nosler"},
            {"name": "5.45×39mm"},
            {"name": "5.6×35mmR Vierling"},
            {"name": "5.66×39mm"},
            {"name": ".218 Bee"},
            {"name": ".220 Russian"},
            {"name": ".22 Hornet"},
            {"name": "5.56×45mm NATO"},
            {"name": ".223 Remington"},
            {"name": "5.6mm GP90 (1990)"},
            {"name": ".222 Remington Magnum"},
            {"name": ".22-250"},
            {"name": ".224 Weatherby Magnum"},
            {"name": ".220 Swift"},
            {"name": ".22 Spitfire"},
            {"name": ".22 Creedmoor"},
            {"name": ".223 WSSM"},
            {"name": "5.6×50mm Magnum (5.6×50mmR)"},
            {"name": "5.6×57mm"},
            {"name": "FN 5.7×28mm"},
            {"name": "22 PPC-USA"},
            {"name": ".219 Zipper"},
            {"name": "224 Valkyrie"},
            {"name": "22 Nosler"},
            {"name": ".22 Savage Hi-Power"},
            {"name": ".221 Remington Fireball"},
            {"name": ".222 Remington"},
            {"name": ".225 Winchester"},
            {"name": ".22 Winchester Centerfire"},
            {"name": "5.8×42mm DBP87"}
          ],
    },
    {
        range: "6mm (.236 - .275)",
        variants: [
            {"name": ".25 ACP (.25 Auto)"},
            {"name": ".25 NAA"},
            {"name": "6.45mm GP80 (1980) 6.45x48mm"},
            {"name": "6.5mm Bergmann"},
            {"name": "6.5×25mm CBJ"},
            {"name": ".243 Winchester"},
            {"name": "6mm BR"},
            {"name": "6×45mm SAW"},
            {"name": "6mm PPC"},
            {"name": "6mm XC"},
            {"name": ".243 WSSM"},
            {"name": "6mm ARC"},
            {"name": "6mm GT"},
            {"name": "6mm Remington (.244 Remington)"},
            {"name": ".240 Weatherby Magnum"},
            {"name": "6mm Creedmoor"},
            {"name": "24 Nosler"},
            {"name": "6mm AR"},
            {"name": "6×45mm"},
            {"name": "6mm Lee Navy"},
            {"name": ".240 Apex"},
            {"name": ".244 H&H Magnum"},
            {"name": ".25-25 Stevens"},
            {"name": ".256 Win Magnum"},
            {"name": ".25-45 Sharps"},
            {"name": ".257 Weatherby Magnum"},
            {"name": ".25 Remington"},
            {"name": "255 GS"},
            {"name": ".25-06 Remington"},
            {"name": ".25 WSSM"},
            {"name": ".25-20 Winchester"},
            {"name": ".25-35 Winchester"},
            {"name": ".250-3000 Savage"},
            {"name": ".257 Roberts"},
            {"name": "6.45×48mm XPL Swiss"},
            {"name": "6.5×58mm Vergueiro"},
            {"name": "6.5×55mm Swedish (aka 6.5×55mm Krag)"},
            {"name": "6.5×57mm Mauser"},
            {"name": "6.5×68mm"},
            {"name": "6.5-284 Norma"},
            {"name": "6.5mm Remington Magnum"},
            {"name": "6.5-06 A-Square"},
            {"name": ".256 Newton"},
            {"name": ".260 Remington"},
            {"name": "6.5mm Creedmoor"},
            {"name": "6.5×47mm Lapua"},
            {"name": "6.5mm Grendel"},
            {"name": ".264 Winchester Magnum"},
            {"name": "6.5×50mmSR Arisaka"},
            {"name": "6.5×54mm Mannlicher–Schönauer"},
            {"name": "6,5 G.A.P. 4S"},
            {"name": "6.5 Weatherby Rebated Precision Magnum"},
            {"name": "6.5 Precision Rifle Cartridge"},
            {"name": "6.5-300 Weatherby Magnum"},
            {"name": "26 Nosler"},
            {"name": "6.5×53mmR"},
            {"name": "6.5×52mm Carcano"}
          ],
    },
    {
        range: "7mm (.276 - .314)",
        variants: [
            {"name": "7×20mm Nambu"},
            {"name": "7.5 FK BRNO"},
            {"name": ".30 AMP"},
            {"name": "7.62×42mm"},
            {"name": "7.65mm Roth–Sauer"},
            {"name": "7.62×25mm Tokarev"},
            {"name": "7.65×25mm Borchardt"},
            {"name": "7.65mm Mannlicher"},
            {"name": "7.63×25mm Mauser"},
            {"name": "7.65mm Longue"},
            {"name": "7.65×21mm Parabellum (7.65 mm Luger)"},
            {"name": "7.65mm Pist Pat 03 7.65x21mm"},
            {"name": "7.92x24mm VBR"},
            {"name": ".32 ACP (7.65 Browning Short)"},
            {"name": ".32 NAA"},
            {"name": ".30 Super Carry"},
            {"name": ".30 Short"},
            {"name": "7.62×38mmR"},
            {"name": ".32 Smith & Wesson"},
            {"name": ".32 Short Colt (.320 Revolver)"},
            {"name": ".32 Long Colt (.32 Colt)"},
            {"name": ".32 S&W Long (.32 Colt New Police)"},
            {"name": ".32 H&R Magnum"},
            {"name": ".327 Federal Magnum"},
            {"name": ".270 British"},
            {"name": ".277 Wolverine"},
            {"name": ".270 Weatherby Magnum"},
            {"name": ".27 Nosler"},
            {"name": ".270 Winchester"},
            {"name": ".270 Winchester Short Magnum"},
            {"name": ".277 FURY"},
            {"name": "6.8mm Remington SPC"},
            {"name": "6.8 Western"},
            {"name": ".276 Enfield"},
            {"name": ".284 Winchester"},
            {"name": "7mm BR Remington (bench rest)"},
            {"name": ".280 British"},
            {"name": ".280/30 British"},
            {"name": "7mm-08 Remington"},
            {"name": "7mm Raptor"},
            {"name": "7mm Remington SAUM"},
            {"name": "7-30 Waters"},
            {"name": "7mm WSM"},
            {"name": "7mm PRC (Precision Rifle Cartridge)"},
            {"name": "7mm Remington Magnum"},
            {"name": "7mm Dakota"},
            {"name": ".280 Remington"},
            {"name": "7mm-06 Remington"},
            {"name": "7mm Remington Express"},
            {"name": "7mm Weatherby Magnum"},
            {"name": "7mm STW (Shooting Times Westerner)"},
            {"name": "7mm Remington Ultra Magnum"},
            {"name": "7x61mm Sharpe & Hart"},
            {"name": ".276 Pedersen"},
            {"name": ".28 Nosler"},
            {"name": ".280 Ackley Improved"},
            {"name": "7×57mm Mauser"},
            {"name": "7mm Mauser Spanish Mauser .275 Rigby"},
            {"name": "7×64mm"},
            {"name": "7×33mm Sako"},
            {"name": ".280 Ross"},
            {"name": "7.35×51mm Carcano"},
            {"name": "7.5x22mmR Nagant"},
            {"name": "7.5×55mm Swiss"},
            {"name": "7.5mm GP11 (1911) 7.5x55mm"},
            {"name": "7.5mm GP90 (1890) 7.5x53mm"},
            {"name": "7.5mm GP90/03 (1890) 7.5x53mm"},
            {"name": "7.5mm GP90/23 (1890) 7.5x53mm"},
            {"name": "7.5mm Rev Pat 82 (1882) 7.5x23mmR"},
            {"name": "7.5x23mmR"},
            {"name": ".30 Carbine"},
            {"name": ".30 Pedersen"},
            {"name": "7.62×40mm Wilson Tactical"},
            {"name": "7.62×51mm NATO"},
            {"name": ".308 Winchester"},
            {"name": ".300 RSAUM"},
            {"name": "7.5×54mm French"},
            {"name": ".30-40 Krag"},
            {"name": ".300 Winchester Magnum"},
            {"name": ".300 Weatherby Magnum"},
            {"name": ".300 H&H Magnum"},
            {"name": ".300 RUM"},
            {"name": ".30-378 Weatherby Magnum"},
            {"name": ".300 Savage"},
            {"name": ".303 Savage"},
            {"name": ".30 Remington"},
            {"name": ".308 Norma Magnum"},
            {"name": ".300 Lapua Magnum"},
            {"name": "30 BR"},
            {"name": ".300 WSM (Winchester Short Magnum)"},
            {"name": ".30 Newton"},
            {"name": "300 Precision Rifle Cartridge"},
            {"name": ".30-06 Springfield"},
            {"name": ".30-03 Springfield"},
            {"name": "300 AAC Blackout"},
            {"name": "300 Ruger Compact Magnum"},
            {"name": ".30-30 Winchester"},
            {"name": "30 Remington AR"},
            {"name": ".307 Winchester"},
            {"name": "300 HAM'R"},
            {"name": "7.62×45mm"},
            {"name": "7.62×53mmR"},
            {"name": ".300 Norma Magnum"},
            {"name": ".300 LRH"},
            {"name": "7.82 Warbird"},
            {"name": ".300 Werewolf"},
            {"name": "7.62×38mmR"},
            {"name": "7.62×39mm M43"},
            {"name": "7.62×54mmR"},
            {"name": ".303 British"},
            {"name": ".32-20 Winchester .32-20 WCF"},
            {"name": "7.65×53mm Argentine"},
            {"name": "7.7×58mm Arisaka"}
          ],
    },
    {
        range: "8mm (.315 - .353)",
        variants: [
            {"name": ".32 ACP (.32 Auto)"},
            {"name": ".30 Super Carry"},
            {"name": "8mm Roth–Steyr"},
            {"name": "8×22mm Nambu"},
            {"name": ".32 S&W (.32 S&W Short)"},
            {"name": ".32 S&W Long"},
            {"name": ".32 H&R Magnum"},
            {"name": ".327 Federal Magnum"},
            {"name": ".320 Revolver"},
            {"name": "7.5mm 1882 Ordnance 7.5mm Swiss Army Revolver"},
            {"name": "8mm French Ordnance 8mm Lebel Revolver 8×27mmR Règlementaire Mle 92"},
            {"name": "7.5mm Swedish Nagant"},
            {"name": ".32 Ballard Extra Long"},
            {"name": ".32-40 Ballard"},
            {"name": "8×52mmR Mannlicher"},
            {"name": "8×50mmR Mannlicher"},
            {"name": ".32 Winchester Self-Loading"},
            {"name": "8×58mmR Danish Krag"},
            {"name": "8×56mmR Kropatschek"},
            {"name": ".32 Winchester Special"},
            {"name": "7.92×33mm Kurz"},
            {"name": ".32 Remington"},
            {"name": ".325 WSM"},
            {"name": "8×57mm IS/8mm Mauser"},
            {"name": "8×60mm S"},
            {"name": "8×63mm patron m/32"},
            {"name": "8×64mm S"},
            {"name": "8×68mm S"},
            {"name": "8mm Remington Magnum"},
            {"name": "8mm Lebel"},
            {"name": "8×56mmR Mannlicher"},
            {"name": "8×59mm RB Breda"},
            {"name": ".333 Jeffery Flanged"},
            {"name": "8.6 mm Blackout"},
            {"name": ".338 Norma Magnum"},
            {"name": ".338 Winchester Magnum"},
            {"name": ".338 Lapua Magnum"},
            {"name": ".338 Whisper"},
            {"name": ".338 Marlin Express"},
            {"name": ".33 Winchester"},
            {"name": ".338-06"},
            {"name": "8,5 × 68 Fanzoj"},
            {"name": "338 Blaser Mag."},
            {"name": ".338 Federal"},
            {"name": ".338 Ruger Compact Magnum"},
            {"name": ".338 Remington Ultra Magnum"},
            {"name": ".338 Edge"},
            {"name": ".338 Weatherby RPM"},
            {"name": ".340 Weatherby Magnum"},
            {"name": ".338-378 Weatherby Magnum"},
            {"name": ".33 Nosler"},
            {"name": ".348 Winchester"}
          ],
    },
    {
        range: "9mm (.354 - .393)",
        variants: [
            {"name": ".380 ACP (.380 Auto; 9x17mm)"},
            {"name": ".960 Rowland"},
            {"name": "9×18mm Ultra"},
            {"name": "9mm Automatic"},
            {"name": "9mm Glisenti"},
            {"name": "9×19mm Parabellum (9mm Luger)"},
            {"name": "9mm Pist Pat 41 9x19mm"},
            {"name": "9mm Pist Pat 14 9x19mm"},
            {"name": "9×30mm Grom"},
            {"name": ".357 SIG"},
            {"name": "9mm Browning Long"},
            {"name": "9×21mm"},
            {"name": "9×21mm Gyurza"},
            {"name": "9mm Action Express"},
            {"name": "9×23mm Steyr"},
            {"name": "9x23mm Largo"},
            {"name": "9×25mm Mauser"},
            {"name": "9×25mm Dillon"},
            {"name": "9mm Winchester Magnum"},
            {"name": "9×25mm Super Auto G"},
            {"name": ".356 TSW"},
            {"name": ".38 ACP (.38 Auto; 9x23mmSR)"},
            {"name": ".38 Super (.38 Super Auto; 9x23mmSR)"},
            {"name": "9×23mm Winchester"},
            {"name": ".38 AMU (.38 Army Marksmanship Unit)"},
            {"name": ".38/.45 Clerke (.38/45 Auto)"},
            {"name": "9×18mm Makarov"},
            {"name": "9mm Federal (9×19mmR)"},
            {"name": "9mm Japanese"},
            {"name": ".38 Short Colt"},
            {"name": ".38 Long Colt"},
            {"name": ".38 S&W Special"},
            {"name": ".357 S&W Magnum"},
            {"name": ".357 SuperMag"},
            {"name": ".357/44 Bain & Davis"},
            {"name": ".357 Remington Maximum"},
            {"name": ".38 S&W (.38 S&W Short)"},
            {"name": ".375 SuperMag"},
            {"name": ".41 Long Colt"},
            {"name": ".35 Winchester Self-Loading"},
            {"name": ".351 Winchester Self-Loading"},
            {"name": "9×57mm Mauser"},
            {"name": ".350 Legend"},
            {"name": ".35 Remington"},
            {"name": ".35 Whelen"},
            {"name": ".356 Winchester"},
            {"name": ".358 Winchester"},
            {"name": "9mm Jonson"},
            {"name": ".35 Winchester"},
            {"name": ".350 Remington Magnum"},
            {"name": ".358 Norma Magnum"},
            {"name": ".360 Buckhammer"},
            {"name": "9×39mm"},
            {"name": ".36 Nosler"},
            {"name": "9.3×57mm Mauser"},
            {"name": "9.3×62mm"},
            {"name": "9.3×64mm Brenneke"},
            {"name": "9.3×66 Sako"},
            {"name": "9.3×72mmR"},
            {"name": "9.3×74mmR"},
            {"name": "9.4x22mmR Nagant"},
            {"name": ".376 Steyr"},
            {"name": ".375 Chey Tac (9.5×77mm)"},
            {"name": ".375 H&H Magnum"},
            {"name": ".375 Remington Ultra Magnum"},
            {"name": ".375 Ruger"},
            {"name": ".375 SWISS P"},
            {"name": ".375 Weatherby Magnum"},
            {"name": ".378 Weatherby Magnum"},
            {"name": ".375 Winchester"},
            {"name": ".38-55 Winchester"},
            {"name": ".38-56 WCF"},
            {"name": ".38-72 Winchester"},
            {"name": ".375-416"},
            {"name": ".375 Snipe Tac"},
            {"name": ".375 SOE"}
          ],
    },
    {
        range: "10mm (.394 - .432)",
        variants: [
            {"name": ".40 S&W"},
            {"name": ".40 Super"},
            {"name": "10mm Auto"},
            {"name": "10mm Magnum"},
            {"name": ".400 Corbon"},
            {"name": ".41 Action Express"},
            {"name": ".44 AMP"},
            {"name": ".38-40 Winchester"},
            {"name": ".41 Short (.41 Rimfire)"},
            {"name": ".41 Short Colt"},
            {"name": ".41 Special"},
            {"name": ".41 Magnum"},
            {"name": ".414 Super Magnum"},
            {"name": "10.4 mm Italian"},
            {"name": "11 mm German Serv"},
            {"name": ".44 Russian"},
            {"name": ".44 Special"},
            {"name": ".44 Magnum"},
            {"name": ".445 Super Magnum"},
            {"name": ".400 Legend"},
            {"name": ".40-60 Winchester"},
            {"name": ".40-72 Winchester"},
            {"name": ".401 Winchester Self-Loading"},
            {"name": "10.3x60R"},
            {"name": "10.3x68 Magnum"},
            {"name": "10.4×47mm Italian M/70 Centerfire"},
            {"name": ".408 Chey Tac"},
            {"name": ".450/400 3 inch Nitro Express"},
            {"name": ".405 Winchester"},
            {"name": "10.4×38mm Swiss Rimfire"},
            {"name": ".416 Barrett"},
            {"name": ".416 Remington Magnum"},
            {"name": ".416 Weatherby Magnum"},
            {"name": ".416 Rigby"},
            {"name": ".416 Ruger"},
            {"name": ".404 Jeffery"},
            {"name": "10.75x68mm Mauser"},
            {"name": ".44-40 Winchester"},
            {"name": ".444 Marlin"}
          ],
    },
    {
        range: "11mm (.433 - .471)",
        variants: [
            {"name": ".45 ACP (.45 Auto)"},
            {"name": ".45 GAP"},
            {"name": ".45 Remington–Thompson"},
            {"name": ".45 Super"},
            {"name": ".45 Winchester Magnum"},
            {"name": ".455 Webley Auto"},
            {"name": ".460 Rowland"},
            {"name": "11.35mm Schouboe"},
            {"name": "11mm French Ordnance"},
            {"name": "11mm German Service"},
            {"name": ".44 S&W Special"},
            {"name": ".44 Remington Magnum"},
            {"name": ".44 S&W Russian"},
            {"name": ".44 S&W American"},
            {"name": ".44 Webley (.442 R.I.C.)"},
            {"name": ".44 Bulldog"},
            {"name": ".44 Colt"},
            {"name": "11.75mm Montenegrin"},
            {"name": ".45 Webley"},
            {"name": ".45 Auto Rim"},
            {"name": ".454 Magnum"},
            {"name": ".45 Schofield (.45 Smith & Wesson)"},
            {"name": ".45 Colt (.45 Long Colt)"},
            {"name": ".454 Casull"},
            {"name": ".460 S&W Magnum"},
            {"name": ".455 Webley (.455 Webley Mk II)"},
            {"name": ".455 Webley (.455 Colt)"},
            {"name": ".450 Adams (.450 Boxer Mk I)"},
            {"name": ".476 Enfield (.476 Eley)"},
            {"name": ".44-40 Winchester"},
            {"name": ".444 Marlin"},
            {"name": "10.75mm Russian Berdan"},
            {"name": "11mm Murata"},
            {"name": ".425 Westley Richards Magnum"},
            {"name": "11.15mm Spanish Remington"},
            {"name": "11mm Belgian Albini"},
            {"name": "11mm Belgian Comblain"},
            {"name": "11.2×72mm Schüler"},
            {"name": "11.2×60mm Schüler (Mauser)"},
            {"name": "10.8×47mmR Martini Target"},
            {"name": "11.15x42mmR M/67 and 11x58mmR M/77 Werndl"},
            {"name": "11mm French Gras"},
            {"name": ".44 Henry"},
            {"name": "11.15mm Mauser"},
            {"name": "11.43mm Turkish"},
            {"name": "11.43mm Egyptian"},
            {"name": "11.4mm Werndl M/73"},
            {"name": ".500/450 Black Powder No.2 Musket"},
            {"name": "11.4mm Brazilian Comblain"},
            {"name": ".450 Bushmaster"},
            {"name": ".45 Raptor"},
            {"name": "11.5mm Spanish Reformado"},
            {"name": "11.7mm Danish Remington"},
            {"name": ".500/450 Magnum Nitro Express"},
            {"name": ".450 No 2 Nitro Express (31⁄2\")"},
            {"name": ".577/450 Martini–Henry"},
            {"name": ".45-75 Winchester"},
            {"name": ".45-70 Government"},
            {"name": "11mm Beaumont M/71/78"},
            {"name": ".450 Marlin"},
            {"name": ".450 Nitro Express (31⁄4\")"},
            {"name": ".458 Winchester Magnum"},
            {"name": ".458 SOCOM"},
            {"name": ".460 Weatherby Magnum"},
            {"name": ".460 Steyr"},
            {"name": ".500/450 No.1 Express"},
            {"name": ".450 Rigby Rimless"},
            {"name": ".45-60 Winchester"},
            {"name": "11.3mm Beaumont M/71"},
            {"name": ".457 Wild West Guns"},
            {"name": ".458 Lott"},
            {"name": ".500/465 Nitro Express"},
            {"name": ".465 H&H Magnum"}
          ],
    },
    {
        range: "12mm (.472 - .510)",
        variants: [
            {"name": ".475 Wildey Magnum"},
            {"name": ".50 Action Express"},
            {"name": ".50 GI"},
            {"name": ".480 Ruger"},
            {"name": ".475 Linebaugh"},
            {"name": ".500 S&W Special"},
            {"name": ".500 Wyoming Express"},
            {"name": ".500 Linebaugh"},
            {"name": ".500 S&W Magnum"},
            {"name": ".500 Bushwhacker"},
            {"name": ".475 A&M Magnum"},
            {"name": ".470 Capstick"},
            {"name": ".476 Nitro Express"},
            {"name": ".470 Nitro Express"},
            {"name": ".475 No. 2 Nitro Express"},
            {"name": ".475 Nitro Express"},
            {"name": ".577/.500 Magnum Nitro Express"},
            {"name": ".50 Beowulf"},
            {"name": ".50 Alaskan"},
            {"name": ".500 Auto Max"},
            {"name": ".505 Gibbs"},
            {"name": ".500 No. 2 Express (.577/500)"},
            {"name": ".500 Jeffery"},
            {"name": ".50 BMG (12.7×99mm NATO)"},
            {"name": ".510 DTC Europ (.50 DTC)"},
            {"name": ".510 Whisper"},
            {"name": "12.7×108mm"},
            {"name": "12.7×55mm STs-130"},
            {"name": "12.7x81mmSR (50 British)"}
          ],
    },
    {
        range: "13mm (.511 +)",
        variants: [
            {"name": "13×64mm"},
            {"name": "13mm Gyrojet"},
            {"name": ".500 Linebaugh"},
            {"name": ".500 Nitro Express"},
            {"name": ".50-90 Sharps"},
            {"name": ".50-110 Winchester"},
            {"name": ".50-140 Sharps"},
            {"name": ".50-70 Government"},
            {"name": "13.2mm TuF (13.2×92mmSR)"},
            {"name": "13.2×99mm Hotchkiss"},
            {"name": ".56-56 Spencer"},
            {"name": "14×33mmR Wänzl"},
            {"name": ".55 Boys (13.9×99mmB)"},
            {"name": ".577 Snider"},
            {"name": ".577 Nitro Express"},
            {"name": ".600/577 Rewa"},
            {"name": ".577 Tyrannosaur"},
            {"name": ".585 Nyati"},
            {"name": "14.5×114mm"},
            {"name": "14.5х148"},
            {"name": "14.5х218"},
            {"name": "14.5mm JDJ"},
            {"name": "15х104 Brno"},
            {"name": "15.24х40R Krnka"},
            {"name": "15.5х106 BRG"},
            {"name": ".600 Nitro Express"},
            {"name": ".600 Overkill"},
            {"name": ".700 Nitro Express"},
            {"name": ".70-150 Winchester"},
            {"name": "20.3х95R Ghan"},
            {"name": "20х150R"},
            {"name": "23×152mmB"},
            {"name": ".950 JDJ (24.1×70mm)"}
          ],
    },
    {
        range: "Flintenmunition",
        variants: [
            {"name": "2 bore: 3+1⁄2 in (89mm)"},
            {"name": "4 bore: 3+1⁄4 in (83mm)"},
            {"name": "4 bore: 4 in (102mm)"},
            {"name": "6 bore"},
            {"name": "8 bore: 3 in (76mm)"},
            {"name": "8 bore: 3+1⁄4 in (83mm)"},
            {"name": "8 bore: 3+3⁄4 in (95mm)"},
            {"name": "8 bore: 4 in (102mm)"},
            {"name": "10 bore: 2+9⁄16 in (65mm)"},
            {"name": "10 bore: 2+5⁄8 in (67mm)"},
            {"name": "10 bore: 2+7⁄8 in (73mm)"},
            {"name": "10 bore: 3 in (76mm)"},
            {"name": "10 bore: 3+1⁄4 in (83mm)"},
            {"name": "10 bore: 3+1⁄2 in (89mm)"},
            {"name": "12 bore: 1+3⁄4 in (44mm)"},
            {"name": "12 bore: 2 in (51mm)"},
            {"name": "12 bore: 2+1⁄4 in (57mm)"},
            {"name": "12 bore: 2+1⁄2 in (64mm)"},
            {"name": "12 bore: 2+3⁄4 in (70mm)"},
            {"name": "12 bore: 3 in (76mm)"},
            {"name": "12 bore: 3+1⁄2 in (89mm)"},
            {"name": "14 bore: 2+1⁄2 in (64mm)"},
            {"name": "16 bore: 2+1⁄2 in (64mm)"},
            {"name": "16 bore: 2+9⁄16 in (65mm)"},
            {"name": "16 bore: 2+5⁄8 in (67mm)"},
            {"name": "16 bore: 2+3⁄4 in (70mm)"},
            {"name": "16 bore: 3 in (76mm)"},
            {"name": "20 bore: 2+1⁄2 in (64mm)"},
            {"name": "20 bore: 2+3⁄4 in (70mm)"},
            {"name": "20 bore: 3 in (76mm)"},
            {"name": "20 bore: 3+1⁄2 in (89mm)"},
            {"name": "24 bore: 2+1⁄2 in (64mm)"},
            {"name": "28 bore: 2+1⁄2 in (64mm)"},
            {"name": "28 bore: 2+3⁄4 in (70mm)"},
            {"name": "28 bore: 3 in (76mm)"},
            {"name": "32 bore: 2+1⁄2 in (64mm)"},
            {"name": ".410 bore: 2 in (51mm)"},
            {"name": ".410 bore: 2+1⁄2 in (64mm)"},
            {"name": ".410 bore: 3 in (76mm)"},
            {"name": ".360 bore: 1+3⁄4 in (44mm)"},
            {"name": "9 mm (No. 3 bore) short rimfire"},
            {"name": "9 mm (No. 3 bore) long rimfire"},
            {"name": "7 mm (No. 2 bore) rimfire"},
            {"name": "6 mm (No. 1 bore) short rimfire"},
            {"name": "6 mm (No. 1 bore) long rimfire"}
          ],         
    },
    {
        range: "Anderes",
        variants: [
            {"name": "Granaten"},
            {"name": "Flechettes"},
            {"name": "Plasma"},
            {"name": "Tennisbälle"},
            {"name": "Dihydrogenmonoxyd"},
            {"name": "Flammen"},
            {"name": "Gummiplömpel"},
            {"name": "Luft & Liebe"}
        ]
    }
]